### ISSUE TITLE
`php` and `nodejs` versions

### ISSUE THREAD

**Issue by drupol** [RikudouSage/NixPackageHistoryFrontend#1]
Hi,

I was recommending your website to a colleague when I noticed something that could be improved. That thing confused myself and also my colleague, and I think there are room for improvements, especially if you think about merging this feature in the official website.

- When typing `php`, it should list _all_ the PHP versions (`php81`, `php82` and `php83`)
- Similarly, when typing `nodejs`, it should list _all_ the PHP versions (`nodejs_18`, `nodejs_19`, `nodejs_20` and `nodejs_21`)

Currently, to list all the PHP 8.3 versions, I need to type `php83`. This is not what I would expect.
Typing `php` should be sufficient to list all the existing versions, same for `nodejs`.

**Comment by RikudouSage** [comment]
It's done, you should now be able to search for grouped packages, currently only `php` and `nodejs`/`node`.
